### ISSUE TITLE
Nextcloud, its database and redis to communicate on selected ports everything else is blocked?

### ISSUE THREAD

**Issue by mannp** [kaysond/trafficjam#14]
Hi there

Thanks for creating this :)

Not sure if the whitelist function is used for this or whether this is a supported config, but how would I config for multiple grouped dockers e.g., Nextcloud, its database and redis, on the same external network behind traefik2?

```
Application1, its db and redis talk amoungst themselves on selected ports only

   -> App1 is blocked from App2 or App3

Application2, its db and redis talk amoungst themselves on selected ports only

   -> App2 is blocked from App1 or App3

Application3, its db and redis talk amoungst themselves on selected ports only

   -> App3 is blocked from App1 or App2
```

**Comment by kaysond** [comment]
That's a very restrictive and complex ruleset that trafficjam just isn't built to support. You could do it manually by forcing docker network parameters (subnet and container IPs) and adding raw iptables rules, but I'd advise against it since it would be prone to errors. 

Do you have to have everything on a single network? Best practice in your case anyways would be a separate, dedicated network for each app (e.g. `app1_net` `app2_net` `app3_net`) for intra-app communication, then another network to connect all the app containers (no redis/db) to traefik (e.g. `traefik_net`). Then you'd run trafficjam on `traefik_net` to prevent apps from communicating.

In general there shouldn't be a need to make firewall rules port specific because each container should only be running a single service and exposing the relevant ports. Any other requests just won't receive a response.

**Comment by mrpops2ko** [comment]
i just wanted to bring up a scenario i had and a silly solution, in case others stumble upon this and also want to repeat it because they for some reason need it

so scenario: you have an exposed web application and you also need to direct db expose

if you use trafficjam then you can only expose one through traefik because if you expose the other it will mean the container is in the same network as traefik too and thus the db / app can't communicate with each other (because of the trafficjam rules)


so a solution i had was to just use multiple instances with multiple tags, something like this 

```
  trafficjam:
    container_name: trafficjam
    image: kaysond/trafficjam
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - traefik-reverse-proxy
    environment:
      NETWORK: a-traefik-public
      WHITELIST_FILTER: "label=BYPASS"
      TZ: Europe/London
      INSTANCE_ID: ONE

  jamstraffic:
    container_name: jamstraffic
    image: kaysond/trafficjam
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - traefik-reverse-proxy
    environment:
      NETWORK: a-traefik-public2
      WHITELIST_FILTER: "label=BYPASS2"
      TZ: Europe/London
      INSTANCE_ID: TWO      
```

and then you just expose each to different networks and you can continue as you were - it does mean that then your applications need 2 networks but if you create 2 separate external networks like this it means that you won't ever have to restart traefik and can just continue to use labels

i've still not found a way to get SSO to work in the container apps when authing against another internal app [authentik ]but i don't think you can if it resides on the ```traefik public``` network as that is by design
